### ISSUE TITLE
Setup

### ISSUE THREAD

**Issue by elpiel** [Technolution/rust-gouda-meetup-1#1]
Hello,
It's a good idea to mention which script should be executed in the `setup_up` directory. I found out by checking the files that I should run the `setup.sh`.

Also for some reason the ARM toolchain hasn't been installed and the GCC is `Not Found` after the bobbin check. I will investigate later.

**Comment by egrtechno** [comment]
Hmm, sorry I didn't see this earlier.

Anyways, the GCC check is 'supposed' to fail. The scripts says so much in the output. Just run 'arm-none-eabi-gcc --version' to see if the toolchain is in your $PATH.

ERwin.

**Comment by elpiel** [comment]
Great, it's there, thank you.
