### ISSUE TITLE
Flicker in the Virtualbox screen with High Sierra

### ISSUE THREAD

**Issue by kbh2** [Technolution/rust-gouda-meetup-1#3]
**The Ubuntu screen in the Virtualbox can flicker when using High Sierra.**

The solution is to use the Xorg server and not the Wayland server by:
   Uncomment the line to disable the Wayland server (and use the Xorg server) :
       File: /etc/gdm3/custom.cong
       Line[10]: WaylandEnable=false

This will solve the problem

**Comment by egrtechno** [comment]
Thanks for leaving this tip. If anyone has the same problem this evening, we'll know what to do.
